name: workflow for testing
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: install node and npm
        run: apt install nodejs npm -y
      
      - name: verify node 
        run: node -v



